-
  name: 'Image Browser (Flownative)'
  uriPattern: 'neos/media/browser/images(/{@action}).{@format}'
  defaults:
    '@package': 'Flownative.Media.Browser'
    '@controller': 'Image'
    '@format': 'html'
    '@action': 'index'
  appendExceedingArguments: TRUE
