Flownative:
  Media:
    Browser:
      bodyClasses: 'neos neos-module media-browser'
      scripts:
        - 'resource://Neos.Neos/Public/Library/jquery/jquery-2.0.3.js'
        - 'resource://Neos.Twitter.Bootstrap/Public/2/js/bootstrap.min.js'
        - 'resource://Neos.Neos/Public/Library/bootstrap-components.js'
        - 'resource://Flownative.Media.Browser/Public/JavaScript/media-browser.js'
      styles:
        - 'resource://Neos.Neos/Public/Styles/Neos.css'
        - 'resource://Flownative.Media.Browser/Public/Styles/MediaBrowser.css'

Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flownative.Media.Browser:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Flownative\Media\Browser\Controller\.*'
    mvc:
      routes:
        'Flownative.Media.Browser': true

  Media:
    thumbnailPresets:
      'Flownative.Media.Browser:Thumbnail':
        maximumWidth: 250
        maximumHeight: 250
      'Flownative.Media.Browser:Preview':
        maximumWidth: 1000
        maximumHeight: 1000

  Neos:
    modules:
      management:
        submodules:
          media:
            controller: 'Flownative\Media\Browser\Controller\AssetController'
            label: 'Flownative.Media.Browser:Main:module.label'
            description: 'Flownative.Media.Browser:Main:module.description'
            icon: 'icon-camera'
            privilegeTarget: 'Flownative.Media.Browser:ManageAssets'
            additionalResources:
              styleSheets:
                - 'resource://Flownative.Media.Browser/Public/Styles/MediaBrowser.css'
    userInterface:
      translation:
        autoInclude:
          Flownative.Media.Browser:
            - 'Main'
